[tool.poetry]
name = "matchvibe"
version = "0.1.0"
description = "MatchVibe - app test your pair vibe!"
authors = ["Tikhomirov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
